-
  name: 'API - View Documentation'
  uriPattern: 'neos/api/documentation.html'
  defaults:
    '@package':    'Avency.Neos.OpenApi'
    '@controller': 'Api'
    '@action':     'index'
    '@format':     'html'
  httpMethods: ['GET']
-
  name: 'API - Generate Documentation'
  uriPattern: 'neos/api/documentation.json'
  defaults:
    '@package':    'Avency.Neos.OpenApi'
    '@controller': 'Api'
    '@action':     'getApiJson'
    '@format':     'json'
  httpMethods: ['GET']
